/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package guice_tutorial_full

import spock.lang.Specification
import com.google.inject.Guice

class TextEditorTest extends Specification {
    def "guice injects the spell checker implementation"() {
        setup:
        def injector = Guice.createInjector(new TextEditorModule())
        def editor = injector.getInstance(TextEditor.class)

        when:
        def spellCheckResult = editor.spellChecker.checkSpelling()

        then:
        spellCheckResult == "you checked spelling!"
    }
}
